{
  config,
  pkgs,
  lib,
  ...
}:
with lib; let
  cfg = config.programs.lite-xl;
in {
  imports = [
    ./plugins.nix
    ./colors.nix
  ];

  options.programs.lite-xl = {
    enable = mkEnableOption "lite-xl";
    package = mkOption {
      type = types.package;
      default = pkgs.lite-xl;
    };

    hm-module-plugin-before = mkOption {
      type = types.lines;
      default = "";
    };
    hm-module-plugin = mkOption {
      type = types.lines;
      default = "";
    };
    hm-module-plugin-after = mkOption {
      type = types.lines;
      default = "";
    };
  };

  config = mkIf cfg.enable {
    home.packages = [cfg.package];
    home.file.".config/lite-xl/plugins/hm-module.lua".text = ''
      -- mod-version:3

      -- autogenerated by lite-xl-home-manager

      -- hm-module-plugin-before
      ${cfg.hm-module-plugin-before}

      -- hm-module-plugin
      ${cfg.hm-module-plugin}

      -- hm-module-plugin-after
      ${cfg.hm-module-plugin-after}
    '';
  };
}
